site_name: HistoryAIToolKit
repo_url: https://github.com/historysciencelab/HistoryAIToolkit
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - include-markdown    


nav:
  - Introduction: index.md
  - "Getting Started": getting_started.md