site_name: HistoryAIToolKit
site_url: https://historyaitoolkit.readthedocs.io/en/latest
site_description: AI toolkit for professional and amateur historians, and for anyone who wishes to contribute to the recording of history by and for the community.
repo_url: https://github.com/historysciencelab/HistoryAIToolkit
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - include-markdown    


nav:
  - Introduction: index.md
  - "Getting Started": getting-started.md
  - "Contributing": contributing.md