[tool.poetry]
name = "historyaitoolkit"
version = "0.0.1"
description = "AI toolkit for professional and amateur historians, and for anyone who wishes to contribute to the recording of history by and for the community."
authors = ["Audrey Roy Greenfeld <audrey@feldroy.com>"]
readme = "README.md"
license= "GPL-2.0-or-later"

[tool.poetry.dependencies]
python = "^3.11"
pydantic-settings = "^2.0.3"
pydantic = "^2.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
sphinx = "^7.2.6"
myst-parser = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
