name: Project Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[test]'
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Lint the code
        run: |
          ruff check .

      - name: Format the code
        run: |
          ruff format .

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg          

      - name: Find and run pytest tests
        run: |
          test_files=$(find ./tests/ -name "*test*.py")
          
          # Run pytest on all found test files
          python -m pytest $test_files
